// flow-typed signature: c87b1f8117329ea0dcf8c68e7076e79d
// flow-typed version: <<STUB>>/graphql-generate-flow-schema-assets_v^0.9.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-generate-flow-schema-assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-generate-flow-schema-assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-generate-flow-schema-assets/src/constants' {
  declare module.exports: any;
}

declare module 'graphql-generate-flow-schema-assets/src/generateEnums' {
  declare module.exports: any;
}

declare module 'graphql-generate-flow-schema-assets/src/generateObjectTypes' {
  declare module.exports: any;
}

declare module 'graphql-generate-flow-schema-assets/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-generate-flow-schema-assets/src/constants.js' {
  declare module.exports: $Exports<'graphql-generate-flow-schema-assets/src/constants'>;
}
declare module 'graphql-generate-flow-schema-assets/src/generateEnums.js' {
  declare module.exports: $Exports<'graphql-generate-flow-schema-assets/src/generateEnums'>;
}
declare module 'graphql-generate-flow-schema-assets/src/generateObjectTypes.js' {
  declare module.exports: $Exports<'graphql-generate-flow-schema-assets/src/generateObjectTypes'>;
}
declare module 'graphql-generate-flow-schema-assets/src/index.js' {
  declare module.exports: $Exports<'graphql-generate-flow-schema-assets/src/index'>;
}
